services:
  - type: web
    name: telegram-news-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8782210764:AAGTmH82vHkDdmvUuUwfz_KluRmNs-CIUd0
      - key: TELEGRAM_CHANNEL
        value: -1003755322295
